name: Check for updates

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: dummy
        run: echo "this exist just so github action knows there is a other workflow due to github quirks"
