name: Build and Push Neutralino Flatpak

on:
  push:
    branches: [ "master" ]
    paths: com.gitlab.KRypt0n_.an-anime-game-launcher.yml
      
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install -y curl gnupg appstream file flatpak flatpak-builder build-essential intltool
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: anime-game.flatpak
        manifest-path: com.gitlab.KRypt0n_.an-anime-game-launcher.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
      name: "Deploy"
      with:
        repository: stable
        flat-manager-url: ${{ secrets.REPO_URL }}
        token: ${{ secrets.REPO_TOKEN }}
